import React, { useState } from "react";
import type { Grade } from "@shared/types";

interface SiteSummary {
  domain: string;
  avgCo2Grams: number;
}

interface ExportData {
  totalCo2Grams: number;
  pageCount: number;
  daysOfData: number;
  topSites: SiteSummary[];
  gradeDistribution: Record<Grade, number>;
}

export function generateSummaryText(data: ExportData): string {
  const lines: string[] = [
    "🌱 My Browsing Footprint — CarbonStamp Report",
    "",
    `📊 ${data.daysOfData} days of browsing`,
    `📄 ${data.pageCount} pages analysed`,
    `💨 ${data.totalCo2Grams.toFixed(1)}g CO₂ total`,
    "",
    "🏆 Top sites by carbon:",
  ];

  for (const site of data.topSites) {
    lines.push(`  • ${site.domain}: ${site.avgCo2Grams.toFixed(2)}g avg/visit`);
  }

  lines.push("");
  lines.push("📋 Grade distribution:");
  const grades: Grade[] = ["A+", "A", "B", "C", "D", "F"];
  for (const grade of grades) {
    const count = data.gradeDistribution[grade] ?? 0;
    if (count > 0) {
      lines.push(`  ${grade}: ${count} pages`);
    }
  }

  lines.push("");
  lines.push("Generated by CarbonStamp — carbonstamp.dev");

  return lines.join("\n");
}

export default function ExportButton(props: ExportData) {
  const [copied, setCopied] = useState(false);

  const handleExport = () => {
    const text = generateSummaryText(props);
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <button className="export-button" onClick={handleExport}>
      {copied ? "Copied!" : "Export Report"}
    </button>
  );
}
